title: Run Java microservices on an AKS
description: This lab walks you through the creation of a Java microservices application on AKS integrated with multiple Azure services
theme: just-the-docs

url: https://Azure-Samples.github.io/java-microservices-aks-lab

aux_links:
  Template Repository: https://github.com/Azure-Samples/java-microservices-aks-lab
